kind: Service
apiVersion: v1
metadata:
  name: mario-nodeport
  namespace: mario
spec:
  type: NodePort
  selector:
    app: mario
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 31080  
